### PR TITLE
Altering Comment Checking Logic

### PR DESCRIPTION
**Pull request by jstruzik**
Before this the logic wasn't triggering the successful status update of the needed :+1:s. It would have to wait for another :+1: to come in... That doesn't make sense.

So now the logic works as follows:
+ A PR can have more than the needed plus ones. EX: (4/2)
+ A PR can never have less than 0 plus ones. EX: (0/2)
+ If a comment has a net of 0 plus ones (EX: " :+1: :-1: ") then we stop logic processing

### CODE REVIEW

**Comment by Rican7** [comment]
Yea, makes sense to me.

LGTM :+1:

**Comment by jstruzik** [comment]
Sadly the plus ones won't work properly until this gets merged and deployed haha.

**Comment by jutaz** [comment]
LGTM :+1: 
giphy-8

**Comment by jutaz** [comment]
No merge rights, tho

**Comment by mcos** [comment]
:+1:

**Comment by jstruzik** [comment]
Tenk you!

**Pull request merged**
